import { AlertTriangle, ArrowRight, BookOpen, CalendarCheck, ChevronDown, ChevronUp, ClipboardList, FileText, Lightbulb, Printer, ShieldAlert, Sparkles, Stethoscope } from 'lucide-react';
import { useState } from 'react';
import ConfidenceGauge from '@/components/ConfidenceGauge';
import Disclaimer from '@/components/Disclaimer';
import RiskBadge from '@/components/RiskBadge';
import { RiskMeter } from '@/components/RiskBadge';
import Timeline from '@/components/Timeline';
import type { PageId } from '@/components/Navbar';
import type { AssessmentResult } from '@/lib/types';

interface Props {
  result: AssessmentResult | null;
  onNavigate: (page: PageId) => void;
}

export default function HealthSummary({ result, onNavigate }: Props) {
  if (!result) {
    return (
      <div className="mx-auto max-w-2xl px-4 py-20 text-center">
        <ClipboardList className="mx-auto h-12 w-12 text-slate-300" />
        <h2 className="mt-4 text-2xl font-bold text-slate-800">No assessment yet</h2>
        <p className="mt-2 text-slate-500">Complete an assessment to see your AI-generated health summary here.</p>
        <button onClick={() => onNavigate('assessment')} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-blue-600 to-cyan-500 px-5 py-2.5 text-sm font-semibold text-white shadow-lg">
          Start Assessment <ArrowRight className="h-4 w-4" />
        </button>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-3xl font-bold text-slate-900">Health Summary</h1>
          <p className="text-slate-500">Generated by 8 collaborating AI agents</p>
        </div>
        <button onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">
          <Printer className="h-4 w-4" /> Print Report
        </button>
      </div>

      <div className="mt-6"><Disclaimer /></div>

      {/* Emergency banner */}
      {result.riskLevel === 'emergency' && (
        <div className="mt-4 flex items-center gap-3 rounded-2xl border-2 border-red-300 bg-red-50 px-5 py-4 animate-fade-up">
          <ShieldAlert className="h-8 w-8 shrink-0 text-red-600" />
          <div>
            <p className="font-bold text-red-800">Emergency detected</p>
            <p className="text-sm text-red-700">{result.emergencyAdvice}</p>
          </div>
        </div>
      )}

      <div className="mt-6 grid gap-6 lg:grid-cols-3">
        {/* Left: risk + confidence */}
        <div className="space-y-6">
          <RiskMeter level={result.riskLevel} score={result.riskScore} />
          <div className="card rounded-2xl p-5 text-center">
            <ConfidenceGauge value={result.confidence} label="AI Confidence" />
            <p className="mt-3 text-xs text-slate-500">{result.reasoning.uncertainty}</p>
          </div>
          <div className="card rounded-2xl p-5">
            <div className="flex items-center gap-2">
              <CalendarCheck className="h-4 w-4 text-emerald-600" />
              <h3 className="text-sm font-bold text-slate-800">Recommended Care</h3>
            </div>
            <p className="mt-2 text-lg font-bold text-slate-900">{result.recommendedSpecialist}</p>
            <p className="mt-1 text-sm text-slate-600">{result.recommendation}</p>
          </div>
        </div>

        {/* Right: details */}
        <div className="space-y-6 lg:col-span-2">
          {/* Chief complaint */}
          <div className="card rounded-2xl p-5">
            <div className="flex items-center gap-2">
              <Stethoscope className="h-4 w-4 text-blue-600" />
              <h3 className="text-sm font-bold text-slate-800">Chief Complaint</h3>
            </div>
            <p className="mt-2 text-slate-800">"{result.chiefComplaint}"</p>
            <div className="mt-3 flex flex-wrap gap-2">
              {result.symptoms.map((s) => (
                <span key={s.key} className="rounded-full bg-blue-50 px-3 py-1 text-xs font-medium text-blue-700">{s.label}</span>
              ))}
            </div>
          </div>

          {/* Possible conditions */}
          <div className="card rounded-2xl p-5">
            <div className="flex items-center gap-2">
              <BookOpen className="h-4 w-4 text-sky-600" />
              <h3 className="text-sm font-bold text-slate-800">Possible Conditions (not a diagnosis)</h3>
            </div>
            <div className="mt-3 space-y-3">
              {result.possibleConditions.map((c, i) => (
                <ConditionRow key={i} {...c} />
              ))}
            </div>
          </div>

          {/* AI Reasoning */}
          <div className="card rounded-2xl p-5">
            <div className="flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-indigo-600" />
              <h3 className="text-sm font-bold text-slate-800">AI Reasoning</h3>
            </div>
            <p className="mt-2 text-sm text-slate-700">{result.reasoning.summary}</p>
            <div className="mt-3 rounded-xl bg-indigo-50/60 p-4">
              <p className="text-xs font-semibold uppercase tracking-wide text-indigo-600">Evidence</p>
              <ul className="mt-1.5 space-y-1">
                {result.reasoning.evidence.map((e, i) => (
                  <li key={i} className="flex gap-1.5 text-sm text-slate-600">
                    <span className="mt-1 h-1 w-1 shrink-0 rounded-full bg-indigo-400" /> {e}
                  </li>
                ))}
              </ul>
            </div>
            <div className="mt-3 flex items-start gap-2 rounded-xl bg-amber-50/70 p-4">
              <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" />
              <div>
                <p className="text-xs font-semibold uppercase tracking-wide text-amber-600">Uncertainty</p>
                <p className="text-sm text-slate-600">{result.reasoning.uncertainty}</p>
              </div>
            </div>
          </div>

          {/* Timeline */}
          <div className="card rounded-2xl p-5">
            <div className="flex items-center gap-2">
              <FileText className="h-4 w-4 text-blue-600" />
              <h3 className="text-sm font-bold text-slate-800">Assessment Timeline</h3>
            </div>
            <div className="mt-4">
              <Timeline events={result.timeline} />
            </div>
          </div>

          {/* Next steps */}
          <div className="card rounded-2xl p-5">
            <div className="flex items-center gap-2">
              <Lightbulb className="h-4 w-4 text-amber-600" />
              <h3 className="text-sm font-bold text-slate-800">Recommended Next Steps</h3>
            </div>
            <ol className="mt-3 space-y-2">
              {result.nextSteps.map((s, i) => (
                <li key={i} className="flex gap-3 text-sm text-slate-700">
                  <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-blue-100 text-xs font-bold text-blue-700">{i + 1}</span>
                  {s}
                </li>
              ))}
            </ol>
          </div>

          {/* Agent trace */}
          <div className="card rounded-2xl p-5">
            <div className="flex items-center gap-2">
              <ClipboardList className="h-4 w-4 text-slate-600" />
              <h3 className="text-sm font-bold text-slate-800">Agent Collaboration Trace</h3>
            </div>
            <div className="mt-3 space-y-2">
              {result.agentTrace.map((step, i) => (
                <TraceRow key={i} step={step} />
              ))}
            </div>
          </div>
        </div>
      </div>

      <div className="mt-6"><Disclaimer /></div>
    </div>
  );
}

function ConditionRow({ name, likelihood, rationale, warningSigns }: { name: string; likelihood: number; rationale: string; warningSigns: string[] }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="rounded-xl border border-slate-100 bg-white/60">
      <button onClick={() => setOpen(!open)} className="flex w-full items-center justify-between px-4 py-3 text-left">
        <span className="font-semibold text-slate-800">{name}</span>
        <span className="flex items-center gap-2">
          <span className="text-xs font-bold text-slate-500">{likelihood}%</span>
          <div className="h-1.5 w-20 overflow-hidden rounded-full bg-slate-100">
            <div className="h-full rounded-full bg-gradient-to-r from-sky-400 to-blue-500" style={{ width: `${likelihood}%` }} />
          </div>
          {open ? <ChevronUp className="h-4 w-4 text-slate-400" /> : <ChevronDown className="h-4 w-4 text-slate-400" />}
        </span>
      </button>
      {open && (
        <div className="border-t border-slate-100 px-4 py-3 animate-fade-in">
          <p className="text-sm text-slate-600">{rationale}</p>
          <p className="mt-2 text-xs font-semibold text-red-600">Warning signs</p>
          <ul className="mt-1 space-y-0.5">
            {warningSigns.map((w, i) => (
              <li key={i} className="flex gap-1.5 text-xs text-slate-600">
                <AlertTriangle className="mt-0.5 h-3 w-3 shrink-0 text-red-400" /> {w}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}

function TraceRow({ step }: { step: AssessmentResult['agentTrace'][number] }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="rounded-xl border border-slate-100 bg-white/60">
      <button onClick={() => setOpen(!open)} className="flex w-full items-center justify-between px-4 py-2.5 text-left">
        <span className="text-sm font-medium text-slate-700">{step.title}</span>
        <span className="flex items-center gap-2">
          <span className="text-[10px] text-slate-400">{step.durationMs}ms</span>
          {open ? <ChevronUp className="h-3.5 w-3.5 text-slate-400" /> : <ChevronDown className="h-3.5 w-3.5 text-slate-400" />}
        </span>
      </button>
      {open && (
        <div className="border-t border-slate-100 px-4 py-3 animate-fade-in">
          <ul className="space-y-1">
            {step.reasoning.map((r, i) => (
              <li key={i} className="flex gap-1.5 text-xs text-slate-600">
                <span className="mt-1 h-1 w-1 shrink-0 rounded-full bg-blue-400" /> {r}
              </li>
            ))}
          </ul>
          <p className="mt-2 rounded-lg bg-emerald-50/70 px-3 py-1.5 text-xs text-slate-700">{step.output}</p>
        </div>
      )}
    </div>
  );
}
